title: CKAD Practice Labs
description: Hands-on lab exercises for CKAD exam preparation
remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme

# GitHub repo link
github:
  repo: uzunenes/CKAD
