theme: jekyll-theme-minimal
title: CKAD Pratik Lablar
description: Kubernetes CKAD sınavına hazırlık için uygulamalı laboratuvar çalışmaları
show_downloads: false
google_analytics:
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
